# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # types: [opened, synchronize, reopened]    

jobs:
  build:
    name: Test #and analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
    - name: Restore dependencies
      run: |
        dotnet restore
      # dotnet tool install --global dotnet-sonarscanner
      # dotnet tool install --global dotnet-coverage
    #- name: Begin analyzing
    #  run: dotnet sonarscanner begin -k:"${{ vars.SONAR_PROJECT }}" -o:"${{ vars.SONAR_ORGANIZATION }}" -d:sonar.token="${{ secrets.SONAR_TOKEN }}" -d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
    - name: Build
      run: dotnet build --no-restore #--no-incremental
    - name: Test
      run: dotnet test --no-build
    #- name: Finish analyzing
    #  run: dotnet sonarscanner end -d:sonar.token="${{ secrets.SONAR_TOKEN }}"
